name: elizabeth_building_committee
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0-52.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gsheets: ^0.3.0-dev.1
  csv: ^5.0.0-nullsafety.0
  gcloud: ^0.7.3
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12+1
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.4-nullsafety.19
