name: elizabeth_building_committee
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

#   --no-sound-null-safety

environment:
  sdk: ^2.16.2

dependencies:
  flutter:
    sdk: flutter
  gsheets:
  csv:
  gcloud:    # gcloud 0.7.3 depends on googleapis >=0.50.2 <1.0.0
  googleapis:
  googleapis_auth:
  excel:
  syncfusion_flutter_xlsio:
  logger:
#  path: ^1.7.0

dev_dependencies:
  pedantic:
  test:
